"""add the relation of users to the books 

Revision ID: cba649263046
Revises: a162f00d8b33
Create Date: 2025-07-07 11:15:24.104319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cba649263046'
down_revision: Union[str, None] = 'a162f00d8b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uuid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_uuid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uuid')
    # ### end Alembic commands ###
